### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by matwey** [comment]
How, this PR is also conflicting. Could you please rebase?

**Comment by flosse** [comment]
> How, this PR is also conflicting. Could you please rebase?

done :)

**Comment by matwey** [comment]
Thanks. Do you plan more updates or I can tag a new version?

**Comment by flosse** [comment]
> Thanks. Do you plan more updates or I can tag a new version?

You can tag a new version :)

And hopefully I'll be able to contribute more updates in the future too ;-)

**Comment by matwey** [comment]
Done. It'll take some time to CI to publish new crate.

**Pull request merged**
